name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt ruff pytest uvicorn

      - name: Lint
        run: ruff check .

      - name: Train smoke (creates model.pkl + metrics.json)
        run: python src/train.py

      - name: API smoke test (/health)
        run: |
          uvicorn src.predict_service:app --host 0.0.0.0 --port 8080 &
          PID=$!
          sleep 2
          curl -fsS http://127.0.0.1:8080/health | tee health.json
          kill $PID

      - name: Unit tests
        run: pytest -q

      - name: Show metrics in logs
        run: cat metrics.json || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: |
            model.pkl
            metrics.json
          retention-days: 7

      - name: Summarize metrics
        if: success()
        run: |
          echo "### Metrics" >> $GITHUB_STEP_SUMMARY
          cat metrics.json >> $GITHUB_STEP_SUMMARY
